import type { Metadata } from "next";
import Image from "next/image";
import "./globals.css";

import { roboto, concertOne } from "./ui/fonts";
import Header from "./ui/rcweb-components/Header";
import Footer from "./ui/rcweb-components/Footer";

export const metadata: Metadata = {
  title: {
    default: "RC WEB",
    template: "%s | RC WEB",
  },
  description: "Generated by create next app",
  keywords: [
    "Software Engineer",
    "Software Developer",
    "Web Developer",
    "Frontend Developer",
    "Fullstack Developer",
    "Backend Developer",
    "React Developer",
    "JavaScript Developer",
    "Next.js Developer",
    "React",
    "Next.js",
    "Tailwind CSS",
    "TypeScript",
    "Zustand",
    "Zod",
    "Shadcn/ui",
    "PostgreSQL",
    "Prisma",
  ],
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth">
      <body
        className={`w-full ${concertOne.variable} ${roboto.variable} overflow-y-scroll antialiased absolute top-0 z-[-2] bg-cocoabrown`}
      >
        <Image
          src="/background.webp"
          alt="background image"
          width={500}
          height={500}
          quality={100}
          priority
          className="fixed w-full h-full object-cover top-0 left-0 -z-10 mix-blend-overlay"
        />
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
