import type { Metadata } from "next";
import "./globals.css";

import { roboto, concertOne } from "./ui/fonts";
import Header from "@/app/ui/home/Header";

export const metadata: Metadata = {
  title: {
    default: "RC WEB",
    template: "%s | RC WEB",
  },
  description: "Generated by create next app",
  keywords: [
    "Software Engineer",
    "Software Developer",
    "Web Developer",
    "Frontend Developer",
    "Fullstack Developer",
    "Backend Developer",
    "React Developer",
    "JavaScript Developer",
    "Next.js Developer",
    "React",
    "Next.js",
    "Tailwind CSS",
    "TypeScript",
    "Zustand",
    "Zod",
    "Shadcn/ui",
    "PostgreSQL",
    "Prisma",
  ],
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth">
      <body
        className={`w-full ${concertOne.variable} ${roboto.variable} overflow-y-scroll antialiased absolute top-0 z-[-2] bg-neutral-950 bg-[radial-gradient(ellipse_80%_80%_at_50%_-20%,rgba(120,119,198,0.3),rgba(255,255,255,0))]`}
      >
        {children}
      </body>
    </html>
  );
}
